import React, { useState } from 'react';
import { BACKEND_URL } from '@/config/env.ts';
import { useQuery } from '@tanstack/react-query';
import { TransferProcess } from '@/types/transfer.ts';
import { toast } from 'sonner';
import { ArrowRightLeft, Loader2 } from 'lucide-react';
import DataTransferCard from '@/components/cards/DataTransferCard.tsx';
import { useAccount, useChainId, useSignMessage } from 'wagmi';
import { createSiweMessage, generateSiweNonce, SiweMessage } from 'viem/siwe';
import { CatalogAsset } from '@/types/catalog.ts';
import { handleApiError } from '@/lib/apiUtils.ts';
import { useAssetsQuery } from '@/hooks/useAssetsQuery.ts';
import { Button } from '@/components/ui/button.tsx';
import { Link } from 'react-router-dom';

const TransfersPage: React.FC = () => {
    const [fetchingTransferId, setFetchingTransferId] = useState<string | null>(null);
    const [signingTransferId, setSigningTransferId] = useState<string | null>(null);
    const { address, isConnected } = useAccount();
    const { signMessageAsync } = useSignMessage();
    const currentChainId = useChainId();

    const { data: assetsData, isLoading: isLoadingAssets } = useAssetsQuery();
    const { data: transfers, isLoading: isLoadingTransfers } = useQuery({
        queryKey: ['transfers'],
        queryFn: async () => {
            const response = await fetch(`${BACKEND_URL}/api/transfers`);
            if (!response.ok) {
                await handleApiError(response);
            }
            return await response.json() as Promise<TransferProcess[]>;
        },
        refetchInterval: 30000,
    });

    const getAssetForTransfer = (assetId: string): CatalogAsset | undefined => {
        if (!assetsData?.assets) {
            return undefined;
        }

        return assetsData.assets.find((asset: CatalogAsset) => asset.id === assetId);
    };

    const generateSIWESignature = async (requiredChainId: number, transfer: TransferProcess) => {
        if (!isConnected || !address) {
            throw new Error('No Ethereum wallet connected. Please connect your wallet.');
        }

        if (currentChainId !== requiredChainId) {
            throw new Error(
                `Please switch to chain ID ${requiredChainId} in your wallet`,
            );
        }

        // Nonce should be generated by the backend (See: https://eips.ethereum.org/EIPS/eip-4361).
        // We generate the nonce client-side for simplicity.
        const nonce = generateSiweNonce();

        const message: SiweMessage = {
            address: address,
            chainId: requiredChainId,
            domain: window.location.host,
            uri: window.location.origin,
            nonce: nonce,
            version: '1',
            statement: `Access data for transfer: ${transfer['@id']}`,
            issuedAt: new Date(),
            expirationTime: new Date(Date.now() + 10 * 60 * 1000),
        };

        const messageToSign = createSiweMessage(message);
        const signature = await signMessageAsync({
            message: messageToSign,
        });

        return {
            signature: signature,
            message: {
                ...message,
            },
        };
    };

    const handleFetchData = async (transfer: TransferProcess) => {
        try {
            const asset = getAssetForTransfer(transfer.assetId);
            if (!asset) {
                // noinspection ExceptionCaughtLocallyJS
                throw new Error(`Asset ${transfer.assetId} not found`);
            }

            if (asset.contractAddress && asset.chainId) {
                setSigningTransferId(transfer['@id']);

                const { signature, message } = await generateSIWESignature(Number(asset.chainId), transfer);

                setSigningTransferId(null);
                setFetchingTransferId(transfer['@id']);

                const response = await fetch(
                    `${BACKEND_URL}/api/transfers/fetch-data`,
                    {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json',
                        },
                        body: JSON.stringify({
                            transferProcessId: transfer['@id'],
                            correlationId: transfer.correlationId,
                            signature: signature,
                            message: message,
                        }),
                    },
                );

                if (!response.ok) {
                    // noinspection ExceptionCaughtLocallyJS
                    await handleApiError(response);
                }

                const data = await response.json();

                toast.success('Data fetched successfully!', {
                    description: 'NFT verification passed',
                    duration: 5000,
                });

                console.log('Fetched data (with NFT verification):', data);
            } else {
                setFetchingTransferId(transfer['@id']);

                const response = await fetch(
                    `${BACKEND_URL}/api/transfers/${transfer['@id']}/fetch-data`,
                );

                if (!response.ok) {
                    // noinspection ExceptionCaughtLocallyJS
                    await handleApiError(response);
                }

                const data = await response.json();

                toast.success('Data fetched successfully!', {
                    description: 'Check the console for the data',
                    duration: 5000,
                });

                console.log('Fetched data (standard):', data);
            }
        } catch (error) {
            console.error('Error fetching data:', error);
            toast.error('Error fetching data', {
                description: error instanceof Error ? error.message : 'Unknown error',
                duration: 5000,
            });
        } finally {
            setFetchingTransferId(null);
            setSigningTransferId(null);
        }
    };

    if (isLoadingTransfers || isLoadingAssets) {
        return (
            <div className="flex items-center justify-center p-8">
                <Loader2 className="w-8 h-8 animate-spin" />
            </div>
        );
    }

    return (
        <div className="grid gap-6">
            <div>
                <h2 className="text-2xl font-bold mb-1">Data Transfers</h2>
                <p className="text-sm text-muted-foreground">
                    View and manage your data transfer processes
                </p>
            </div>

            {transfers && transfers.length > 0 ? (
                <div className="grid sm:grid-cols-1 lg:grid-cols-2 xl:grid-cols-3 gap-4">
                    {transfers.map((transfer) => {
                        const asset = getAssetForTransfer(transfer.assetId);
                        const requiresSigning = asset
                            ? Boolean(asset.contractAddress && asset.chainId)
                            : false;

                        return (
                            <DataTransferCard
                                key={transfer['@id']}
                                transfer={transfer}
                                onFetchData={handleFetchData}
                                isFetching={fetchingTransferId === transfer['@id']}
                                isSigning={signingTransferId === transfer['@id']}
                                requiresSigning={requiresSigning}
                            />
                        );
                    })}
                </div>
            ) : (
                <div className="flex flex-col items-center justify-center p-12 text-center border rounded-lg">
                    <ArrowRightLeft className="w-16 h-16 text-muted-foreground mb-4" />
                    <h3 className="text-xl font-semibold mb-2">No data transfers found</h3>
                    <p className="text-muted-foreground max-w-md mb-4">
                        Initiate transfers from the Agreements page.
                    </p>
                    <Button asChild>
                        <Link to="/agreements">Go to Agreements</Link>
                    </Button>
                </div>
            )}
        </div>
    );
};

export default TransfersPage;
